FROM nginx:latest
COPY ./index.html /usr/share/nginx/html/index.html
#COPY nginx.conf.template /etc/nginx/nginx.conf.template
# Entrypoint script to replace environment variables in the template
#COPY entrypoint.sh /usr/local/bin/entrypoint.sh
#RUN chmod +x /usr/local/bin/entrypoint.sh

# Expose port 80 and 443
#EXPOSE 80 443

#CMD ["/usr/local/bin/entrypoint.sh"]